# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./portfolio-app/
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'portfolio-app/package-lock.json'
    - name: Install dependencies
      run: npm install  # Change to your actual app directory path
    - name: Build the project
      run: npm run build # Change to your actual app directory path
    - name: Run tests
      run: npm test
    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build
